{% set name = "dnabot" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/BASIC-DNA-ASSEMBLY/DNA-BOT/archive/refs/tags/{{ version }}.tar.gz
  sha256: 0c5d2603b277d09c0a091c714a37c5304f6a1377c2885e9d695f86966be393c0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python >3.6, <=3.9
    - pip
  run:
    - python >3.6, <=3.9
    - aiohttp =3.7.4
    - async-timeout =3.0.1
    - attrs =19.3.0
    - chardet =3.0.4
    - idna
    - importlib-metadata
    - jsonschema
    - more-itertools =7.2.0
    - multidict
    - numpy
    - pandas
    - pyrsistent
    - pyserial =3.4
    - python-dateutil =2.8.0
    - pytz =2019.3
    - six
    - urwid
    - yarl
    - zipp =0.6.0
    - pyyaml
    - xorg-libx11

test:
  source_files:
    - tests
  imports:
    - dnabot
  requires:
    - pytest
  commands:
    - python -m dnabot.dnabot_app --help
    - python -m pytest tests

about:
  home: https://github.com/BASIC-DNA-ASSEMBLY/DNA-BOT
  summary: DNA assembly using BASIC on OpenTrons (DNA-BOT)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tduigou
    - kenza12
