{% set name = "dnabot" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/BASIC-DNA-ASSEMBLY/DNA-BOT/archive/refs/tags/{{ version }}.tar.gz
  sha256: 7d09785a027817834a7ebd9ddb513ddb3bb94e442e50dff636634f9008c3e6bd

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - pyyaml
    - xorg-libx11
    - tabulate
    - astunparse

test:
  source_files:
    - tests
  imports:
    - dnabot
  requires:
    - pytest
    - python {{ python_min }}
  commands:
    - python -m dnabot.dnabot_app --help
    - python -m pytest tests

about:
  home: https://github.com/BASIC-DNA-ASSEMBLY/DNA-BOT
  summary: DNA assembly using BASIC on OpenTrons (DNA-BOT)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tduigou
    - kenza12
