{% set name = "dnabot" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/BASIC-DNA-ASSEMBLY/DNA-BOT/archive/refs/tags/{{ version }}.tar.gz
  sha256: e6794169b7bae895a459f5fee60759c8661e47fd9a77a8d4084a07a660ecffe9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python >3.6
    - pip
  run:
    - python >3.6
    - numpy
    - pandas
    - pyyaml
    - xorg-libx11
    - tabulate

test:
  source_files:
    - tests
  imports:
    - dnabot
  requires:
    - pytest
  commands:
    - python -m dnabot.dnabot_app --help
    - python -m pytest tests

about:
  home: https://github.com/BASIC-DNA-ASSEMBLY/DNA-BOT
  summary: DNA assembly using BASIC on OpenTrons (DNA-BOT)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tduigou
    - kenza12
